---
title: "Assessment Project Document"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="note">
 A multi-sectoral needs assessment must be carefully planned to maximize efficiency and ensure actionable results. The first – and perhaps most important – step of this plan is to ensure all elements of the process are documented. Keeping this in mind from the beginning will prevent a frantic dash later on, when reporting to donors or answering evaluations.
</div>


The project document should:
 * 	clearly state the assessment objectives;
 * 	outline the governance structure, including roles and responsibilities;
 * 	define the methodology to be employed (population sample, tools, etc.)
 * 	provide an overview of staffing needs, budget, and timeline. 

The document can be updated throughout the exercise. 



##  Background and Objective 

In UNHCR’s work around the world, multi-sectoral needs assessments are designed to collect statistically sound, internationally comparable estimates of key indicators and analysis that are used to assess overall situation of PoCs,  and to shape and prioritize appropriate interventions. Data should always be collected for a clear purpose, and only when necessary. 



## Governance Structure 

From the outset, it’s important to define roles and responsibilities. This is true of single-agency and joint assessments. In recent years, joint assessments have become more of a reality, and they are an important element of the Grand Bargain commitment to coordinated needs assessments. Despite a number of benefits, joint assessments can at times be challenging. It is important to establish a strong governance structure from the beginning, often outlined in a Terms of Reference (ToR). Even single-agency assessments are often conducted in collaboration with other parties, such as the government, external contractors, etc. A ToR document for any assessment should: 

* Give the name and type (government agency or other agency) of implementing agency.

* Provide overview of Memorandum of Understanding (MoU) (Parties, critical components affecting survey planning, etc.)

* Give the names and affiliations of those who will be responsible for the management, technical work, and coordination activities. Include the survey coordinator, the sampling expert, and data processing expert assigned from the implementing agency, as well as others, if applicable. If applicable, regional experts/consultants together with their respective responsibilities should also be included.

* Describe the roles and contributions of national and international stakeholders and funding agencies.

* Describe the status, composition and roles and responsibilities of the Steering and Technical committees.

* Provide other details on the governance structure and human resources as needed.


# Methodology

## Data analysis plan

A data analysis plan should be devised in the early stages of assessment planning. Rather than deciding on questions first, indicators must be determined in line with the information needs. Starting with the data analysis plan will avoid unpleasant surprises at the end of data collection, when you realise a certain important question might have been left out! Additionally, if the data analysis plan is linked to the tool from the outset, this will save time in data processing and analysis. 


## Tool  

While UNHCR does not have a standardized tool for multi-sectoral needs assessments, many questionnaires used in different countries are similar to each other, primarily due to cross-pollination of staff and regional experts. Tools can be easily adapted according to operational needs. 
Once your indicators are defined, questions can be chosen, preferably from the IHSN. 

UNHCR’s corporate tool for data collection is Kobo. The assessment focal point and other relevant staff should create an account on [kobo.unhcr.org](https://kobo.unhcr.org/accounts/register/#/)

Provide information on the plans for the translation and back-translation of the questionnaires into local languages and plans for pre-testing the questionnaires. Indicate that the pre-test results will be compiled in a report, and that the results of the pre-test will be used to further modify, customize, and finalize the questionnaires.




## Sample Design 


Sample design is crucial for usability of results. A badly designed or implemented sample can result in the findings not being applicable in the way that was originally intended, be it at geographical, demographic or any other level. Support for sample design can be requested from regional offices, and HQ (more specifically FICCS). Do not hesitate to reach out for support!

UNHCR has also created a [Sampling Decision Assistant](https://unhcr-sampling-assistant.firebaseapp.com/#/home) to help in getting a general idea of how many households should be surveyed in your assessment:

Any sampling strategy, however, should still be validated by technical experts prior to implementation. 

Documenting the sampling strategy is also very important for posterior use of the dataset in other studies. 
In this section, under separate sub-headings, as appropriate, describe:
 * 	The Type of sampling design (Rationale for sampling design explained)
 * 	Definition of unit (case/household) used in the assessment
 * 	Sample size, including the expected numbers of households, women, men and other demographic characteristics as appropriate. 
 * 	How the sample size was calculated, including the indicators used for the calculation of the sample size
 * 	The level of disaggregation sought for reporting
 * 	What sample frame will be used and if the sample frame needs to be updated, plans for mapping, listing and household selection




## Staffing needs

UNHCR commonly relies on partners/third parties for large data collection exercises. This section of the document can be completed jointly, with each party submitting inputs as appropriate. 


In this section, under separate sub-headings as appropriate, describe:

 * Plans for recruitment of fieldwork staff, including details of the type of personnel (interviewers, data entry, supervisors, measurers, data entry clerks), their education/background, sex, numbers etc.
 * Timing of training
 * Length of training
 * Methodology and content of training
 * Profiles of trainers
 * How training will be organized – central location, in separate districts, including how standardization will be ensured if not central location


##	Fieldwork

In this section, under separate sub-headings as appropriate, describe:

 * Timing of fieldwork, constraints on timing of fieldwork
 * Team composition, including numbers
 * Expected duration of fieldwork and how the duration was calculated
 * Plans for monitoring data collection and fieldwork supervision as well as plans for handling questionnaires for data entry 
 * Fieldwork logistics


##	Budget

In this section, under separate sub-headings as appropriate, describe:

 * Expected total cost of the survey
 * Breakdown of total cost by budget line items 
 * Amount of funding secured and funding source(s)
 * Amount of extra funding needed, including plans, if any, on how the funding shortfall will be secured


## Timeline  for Tasks
 * Identify survey coordinator, survey personnel, and plan survey; establish steering and technical committees
 * Adapt and pre-test questionnaires; translate questionnaires and manuals
 * Carry out sampling and household listing; order scales, boards, salt test kits, and GPS equipment
 * Complete logistical arrangements
 * Select and train fieldwork personnel (interviewers, editors, measurers, and supervisors)
 * Conduct pilot study and collect data
 * Complete data processing, including secondary editing
 * Prepare summary findings report and final report, and disseminate widely; prepare survey archive


