---
title: "Managing Devices"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```



## Android Devices 

The software platform used for the data consolidation has specific clients developped on the Android Mobile Operating System. It's also possible, although not first recommended to use any browser (including any browser on a smartphone) to record information.

A certain number of smartphones or tablets will be needed for each survey team to have one or two phones, as well as a few backups. 

For ease of use, smartphones and tablets with a large touchscreen and slide-out keyboard are preferable. Equipement might be borrowed from UNHCR HQ, or country operations could have their own set of phones.

Minimal Requirements for the devices:

* Android Version 2.3 (recent phones are generally platform 4 or higher)
* Screen size of 4 inches is recommended
* GPS Chipset
* Wifi connection

Required Applications:

* Latest recommended version of KoboCollect
* GPS Test, if you need GPS coordinates for the survey
* Andexplorer (or equivalent file explorer)

## Computer

We strongly recommend to have a dedicated survey computer. 
This computer will be set up specifically for the survey. Note that using the computer for other purposes (e.g. internet) may cause compromise the security of the data you will collect.

Minimal Requirements:

* 4G RAM
* Installed with Windows 7 (alternatively XP works as well)

Software Required:

* Microsoft Excel (English Version)
* R 
* Rstudio
* Github


## STEADY POWER SUPPLY

Access to a good electrical supply is essential for the router and computer and for over-night charging capacities of the phones. Where electrical supply is unstable with unexpected power-cuts or planned power savings, alternative charging options must be considered before the survey.

## USB BATTERY PACKS

Even though they cannot replace steady electrical power, battery packs are a useful secondary source of energy for the phones. We recommend having at least 2 for a survey where the phones are daily charged. This way, if a phone lack battery during the survey, the enumerator can charge it while continuing the survey.
